name: test_cov_console
description: Command line utility to read lcov.info and print the coverage report to console.
version: 0.2.2
homepage: https://github.com/DigitalKatalis/test_cov_console

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  test_cov_console:

dev_dependencies:
  test:
